### ISSUE TITLE
Mapper with object list

### ISSUE THREAD

**Issue by rasmus-dybmose** [cc-nogueira/flutter_layered_template#1]
I have a question.
how would you handle relations when mapping?

If ThingModel has a list of OtherModels, how do you map it to a ThingEntity with a list of OtherEntities?
and the other way around like a many to many relation
```
/// Map [ThingEntity] entities to/from Isar [ThingModel] objects.
class ThingMapper extends EntityMapper<ThingEntity, ThingModel> {
  /// Const constructor.
  const ThingMapper();

  /// Othermapper
  final otherMapper = const OtherMapper();

  /// Convert model to entity.
  @override
  ThingEntity mapEntity(ThingModel model) {
    return ThingEntity (
      id: model.id,
      name: model.name,
      description: model.description,
      created: model.created,
      others: otherMapper.mapEntities(model.others),
    );
  }

  /// Convert entity to model.
  @override
  ThingModel mapModel(ThingEntity entity) {
    return ThingModel()
      ..id = entity.id
      ..name = entity.name
      ..description = entity.description
      ..others = otherMapper.mapModels(entity.others);
  }
}
```

```
/// Map [OtherEntity] entities to/from Isar [OtherModel] objects.
class OtherMapper extends EntityMapper<OtherEntity, OtherModel> {
  /// Const constructor.
  const OtherMapper();

  /// Thingmapper
  final thingMapper = const ThingMapper();

  /// Convert model to entity.
  @override
  otherEntity mapEntity(otherModel model) {
    return OtherEntity (
      id: model.id,
      name: model.name,
      description: model.description,
      created: model.created,
      things: thingMapper.mapEntities(model.things),
    );
  }

  /// Convert entity to model.
  @override
  otherModel mapModel(otherEntity entity) {
    return OtherModel()
      ..id = entity.id
      ..name = entity.name
      ..description = entity.description
      ..things = thingMapper.mapModels(entity.things);
  }
}
```

btw I really like your code, keep up the good work! :D

**Comment by cc-nogueira** [comment]
Hi Rasmus.

Mappers and Models are pretty straightforward, the catch is how your persistence framework deals with relations.
In the past I used to choose ObjectBox for persistence, now I am moving to ISAR.

The main difference lies in Repository implementation classes. ISAR has the concept of "Embedded Objects" for simplified 1->N nested objects in a "belongs-to relationship". Here the child cannot be referenced but from it's owner. These are very easy to use, child objects don't have a key field and belongs to the parent.

On a more general approach, where children have their life cycle independent of an owner parent, both ObjectBox and Isar have support for relations:
  - ObjectBox uses the ToMany< Child > and ToOne< Parent > attributes in Model classes.  
  - Isar calls them Links: IsarLinks< Child > and IsarLinks< Parent >.  

Both use annotations in the parent object with the name of the child property that points to the parent for 1-N relations.
  - ObjectBox: @Backlink('parent')
  - Isar: @Backlink(to: 'parent') 

In my experience with ObjectBox I faced some complexity in the Repository implementation to deal with Many relations, particularly when updating an existing object when it is possible to have new relations, removed relations and unchanged relations. Sometimes the new relation is to an existing object in the database, sometimes it is to a new child that has to be persisted just before the parent is updated. But I regard this complexity as "required".

I have not used One-To-Many or Many-To-Many with ISAR to be able to compare the API and possible complications.
It is in my plans to convert an ObjectBox complex model to ISAR and then be able to compare implementations and publish a Flutter tutorial o some kind.


Since you asked about the mapper for OneToMany relations, I am posting bellow mappers for an ObjectBox real implementation I used in a private project. ISAR counterpart would be very similar.

```dart
import '../../../domain.dart';
import '../model/recipe_models.dart';

class RecipeMapper extends EntityMapper<Recipe, RecipeModel> {
  /// Const constructor.
  const RecipeMapper();

  final _ingredientMapper = const RecipeIngredientMapper();

  @override
  Recipe mapEntity(RecipeModel model) {
    return Recipe(
      id: model.id,
      name: model.name,
      description: model.description,
      pinned: model.pinned,
      inTrash: model.inTrash,
      ingredients: _ingredientMapper.mapEntities(model.ingredients..sort((a, b) => a.order.compareTo(b.order))),
    );
  }

  @override
  RecipeModel mapModel(Recipe entity) {
    final model = RecipeModel(
      id: entity.id,
      name: entity.name,
      description: entity.description,
      pinned: entity.pinned,
      inTrash: entity.inTrash,
    );

    final ingredientModels = _ingredientMapper.mapModels(entity.ingredients);
    for (var i = 0; i < ingredientModels.length; ++i) {
      ingredientModels[i].order = i;
    }
    model.ingredients.addAll(ingredientModels);

    return model;
  }
}

class RecipeIngredientMapper extends EntityMapper<RecipeIngredient, RecipeIngredientModel> {
  /// Const constructor.
  const RecipeIngredientMapper();

  @override
  RecipeIngredient mapEntity(RecipeIngredientModel model) {
    return RecipeIngredient(
      id: model.id,
      name: model.name,
      isReferenceWeight: model.isReferenceWeight,
      percentage: model.percentage,
    );
  }

  @override
  RecipeIngredientModel mapModel(RecipeIngredient entity) {
    final model = RecipeIngredientModel(
      id: entity.id,
      name: entity.name,
      isReferenceWeight: entity.isReferenceWeight,
      percentage: entity.percentage,
      order: 0,
    );
    return model;
  }
}


```
